-- Users table
CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    student_id TEXT,
    branch TEXT,
    semester TEXT,
    cgpa REAL,
    previous_sgpa REAL,
    backlogs INTEGER DEFAULT 0,
    role TEXT NOT NULL DEFAULT 'student',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Subscription plans
CREATE TABLE IF NOT EXISTS plans (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    price REAL NOT NULL,
    features TEXT NOT NULL
);

-- User subscriptions
CREATE TABLE IF NOT EXISTS subscriptions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    plan_id INTEGER NOT NULL,
    start_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    end_date TIMESTAMP NULL,
    status TEXT NOT NULL DEFAULT 'active',

    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (plan_id) REFERENCES plans(id)
);

-- Default plans
INSERT INTO plans (name, price, features)
VALUES
    ('Free', 0, 'Free courses, Basic dashboard'),
    ('Basic', 199, 'Free courses, Basic courses, Study resources'),
    ('Premium', 399, 'All courses, Premium courses, All study resources')
ON CONFLICT (name) DO NOTHING;